[package]
name = "sse_pubsub_token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libhydrogen = "0.4.1"
pbkdf2 = "0.11.0"
snafu = "0.7.3"
snafu-derive = "0.7.3"